language: c
compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libpulse-dev portaudio19-dev libsonic-dev
  - sudo gem install ronn

script:
  - ./autogen.sh
  - ./configure
  - make
